version: '3.1'

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "Iamdeveloper"
      MYSQL_DATABASE: "express-sequelize-crud"
      MYSQL_PASSWORD: "Iamdeveloper"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./sql-files/:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "Iamdeveloper"
    ports:
      - "8080:80"
  
volumes:
  mysql_data:
